;; -*- mode: eask; lexical-binding: t -*-

(package "pipmon"
         "1.0.0"
         "A major mode for triggering and monitoring Gitlab pipelines")

(website-url "https://github.com")
(keywords "gitlab")

(package-file "pipmon.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "dash")
(depends-on "pyvenv")

(files "*.el" "pipmon")